import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  backButtonText: {
    fontSize: 18,
    color: '#fff',
    fontWeight: '300',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
    letterSpacing: 1,
  },
  sunArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 60,
  },
});

export const sunStyles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  coronaOuter: {
    position: 'absolute',
    overflow: 'hidden',
  },
  coronaRays: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ray: {
    position: 'absolute',
    borderRadius: 100,
  },
  coronaMiddle: {
    position: 'absolute',
    opacity: 0.4,
  },
  sunBody: {
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 40,
    elevation: 20,
  },
  highlight: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  face: {
    alignItems: 'center',
    marginTop: 10,
  },
  eyes: {
    flexDirection: 'row',
    gap: 20,
  },
  eye: {
    backgroundColor: '#1a1a2e',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pupil: {
    backgroundColor: '#0d0d1a',
    borderRadius: 100,
  },
  eyeShine: {
    position: 'absolute',
    top: 3,
    right: 3,
    backgroundColor: '#fff',
    borderRadius: 100,
  },
  mouthHappy: {
    backgroundColor: '#1a1a2e',
    marginTop: 12,
  },
  mouthNeutral: {
    backgroundColor: '#1a1a2e',
    marginTop: 15,
    borderRadius: 2,
  },
  mouthSad: {
    backgroundColor: '#1a1a2e',
    marginTop: 18,
  },
});

export const dirStyles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tiltPillWrapper: {
    position: 'absolute',
    top: 20,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
    elevation: 100,
  },
  tiltPill: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'rgba(255, 180, 100, 0.5)',
    gap: 4,
    shadowColor: '#FFB464',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  rotatePill: {
    position: 'absolute',
    bottom: 20,
    zIndex: 100,
    elevation: 100,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'rgba(255, 180, 100, 0.5)',
    gap: 12,
    shadowColor: '#FFB464',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  perfectPill: {
    position: 'absolute',
    bottom: 20,
    zIndex: 100,
    elevation: 100,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'rgba(34, 197, 94, 0.8)',
    gap: 12,
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  arrow: {
    fontSize: 32,
    color: '#FFB464',
    fontWeight: '600',
  },
  text: {
    fontSize: 14,
    color: '#FFB464',
    fontWeight: '700',
    letterSpacing: 2,
  },
  perfectIcon: {
    fontSize: 32,
    color: '#22c55e',
    fontWeight: '700',
  },
  perfectText: {
    fontSize: 20,
    color: '#22c55e',
    fontWeight: '700',
    letterSpacing: 3,
  },
});